<?php

namespace ContainerKD3Ra6C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LyXOnwdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lyXOnwd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lyXOnwd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CommentController::commentVote' => ['privates', '.service_locator.B2N.LKQ', 'get_ServiceLocator_B2N_LKQService', true],
            'App\\Controller\\QuestionController::homepage' => ['privates', '.service_locator.TAuaaPl', 'get_ServiceLocator_TAuaaPlService', true],
            'App\\Controller\\QuestionController::questionVote' => ['privates', '.service_locator.qqCANCy', 'get_ServiceLocator_QqCANCyService', true],
            'App\\Controller\\QuestionController::show' => ['privates', '.service_locator.WSbH3C6', 'get_ServiceLocator_WSbH3C6Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\CommentController:commentVote' => ['privates', '.service_locator.B2N.LKQ', 'get_ServiceLocator_B2N_LKQService', true],
            'App\\Controller\\QuestionController:homepage' => ['privates', '.service_locator.TAuaaPl', 'get_ServiceLocator_TAuaaPlService', true],
            'App\\Controller\\QuestionController:questionVote' => ['privates', '.service_locator.qqCANCy', 'get_ServiceLocator_QqCANCyService', true],
            'App\\Controller\\QuestionController:show' => ['privates', '.service_locator.WSbH3C6', 'get_ServiceLocator_WSbH3C6Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\CommentController::commentVote' => '?',
            'App\\Controller\\QuestionController::homepage' => '?',
            'App\\Controller\\QuestionController::questionVote' => '?',
            'App\\Controller\\QuestionController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CommentController:commentVote' => '?',
            'App\\Controller\\QuestionController:homepage' => '?',
            'App\\Controller\\QuestionController:questionVote' => '?',
            'App\\Controller\\QuestionController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
