<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKD3Ra6C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKD3Ra6C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKD3Ra6C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKD3Ra6C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKD3Ra6C\App_KernelDevDebugContainer([
    'container.build_hash' => 'KD3Ra6C',
    'container.build_id' => 'c8201933',
    'container.build_time' => 1646244016,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKD3Ra6C');
